/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowParkingHome (void)
{
  GtkWidget *windowParkingHome;
  GtkWidget *fixed1;
  GtkWidget *treeviewParkingHome;
  GtkWidget *ParkingSearchTextField;
  GtkWidget *eventbox1;
  GtkWidget *buttonAjouterParkingW;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *eventbox2;
  GtkWidget *buttonStatistiqueParkingW;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image13;
  GtkWidget *label28;
  GtkWidget *eventbox3;
  GtkWidget *buttonModifierParkingW;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *eventbox4;
  GtkWidget *buttonSupprimerParkingW;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *eventbox5;
  GtkWidget *buttonActualiserParkingW;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *eventbox6;
  GtkWidget *buttonRechercheParking;
  GtkWidget *image7;
  GtkWidget *eventbox7;
  GtkWidget *ParkingFiltreTextField;
  GtkWidget *eventbox8;
  GtkWidget *buttonFiltreParking;
  GtkWidget *image6;
  GtkWidget *eventbox9;
  GtkWidget *label1;
  GtkWidget *eventbox10;
  GtkWidget *buttonReturnMenuParking;
  GtkWidget *image8;

  windowParkingHome = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowParkingHome), _("Gestion Parking"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowParkingHome), fixed1);
  gtk_widget_set_size_request (fixed1, 943, 810);

  treeviewParkingHome = gtk_tree_view_new ();
  gtk_widget_show (treeviewParkingHome);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewParkingHome, 416, 240);
  gtk_widget_set_size_request (treeviewParkingHome, 464, 384);

  ParkingSearchTextField = gtk_entry_new ();
  gtk_widget_show (ParkingSearchTextField);
  gtk_fixed_put (GTK_FIXED (fixed1), ParkingSearchTextField, 400, 184);
  gtk_widget_set_size_request (ParkingSearchTextField, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ParkingSearchTextField), 8226);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox1, 64, 528);
  gtk_widget_set_size_request (eventbox1, 216, 31);

  buttonAjouterParkingW = gtk_button_new ();
  gtk_widget_show (buttonAjouterParkingW);
  gtk_container_add (GTK_CONTAINER (eventbox1), buttonAjouterParkingW);
  gtk_widget_set_size_request (buttonAjouterParkingW, 216, 31);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAjouterParkingW), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox2, 64, 592);
  gtk_widget_set_size_request (eventbox2, 216, 32);

  buttonStatistiqueParkingW = gtk_button_new ();
  gtk_widget_show (buttonStatistiqueParkingW);
  gtk_container_add (GTK_CONTAINER (eventbox2), buttonStatistiqueParkingW);
  gtk_widget_set_size_request (buttonStatistiqueParkingW, 216, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonStatistiqueParkingW), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image13 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox10), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Affectation"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox10), label28, FALSE, FALSE, 0);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox3, 64, 656);
  gtk_widget_set_size_request (eventbox3, 216, 32);

  buttonModifierParkingW = gtk_button_new ();
  gtk_widget_show (buttonModifierParkingW);
  gtk_container_add (GTK_CONTAINER (eventbox3), buttonModifierParkingW);
  gtk_widget_set_size_request (buttonModifierParkingW, 216, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonModifierParkingW), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox4, 64, 720);
  gtk_widget_set_size_request (eventbox4, 216, 32);

  buttonSupprimerParkingW = gtk_button_new ();
  gtk_widget_show (buttonSupprimerParkingW);
  gtk_container_add (GTK_CONTAINER (eventbox4), buttonSupprimerParkingW);
  gtk_widget_set_size_request (buttonSupprimerParkingW, 216, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonSupprimerParkingW), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox5, 728, 712);
  gtk_widget_set_size_request (eventbox5, 136, 32);

  buttonActualiserParkingW = gtk_button_new ();
  gtk_widget_show (buttonActualiserParkingW);
  gtk_container_add (GTK_CONTAINER (eventbox5), buttonActualiserParkingW);
  gtk_widget_set_size_request (buttonActualiserParkingW, 136, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonActualiserParkingW), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 576, 184);
  gtk_widget_set_size_request (eventbox6, 66, 29);

  buttonRechercheParking = gtk_button_new ();
  gtk_widget_show (buttonRechercheParking);
  gtk_container_add (GTK_CONTAINER (eventbox6), buttonRechercheParking);
  gtk_widget_set_size_request (buttonRechercheParking, 66, 29);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (buttonRechercheParking), image7);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox7, 664, 184);
  gtk_widget_set_size_request (eventbox7, 189, 29);

  ParkingFiltreTextField = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ParkingFiltreTextField);
  gtk_container_add (GTK_CONTAINER (eventbox7), ParkingFiltreTextField);
  gtk_widget_set_size_request (ParkingFiltreTextField, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("monastir"));

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox8, 864, 184);
  gtk_widget_set_size_request (eventbox8, 66, 29);

  buttonFiltreParking = gtk_button_new ();
  gtk_widget_show (buttonFiltreParking);
  gtk_container_add (GTK_CONTAINER (eventbox8), buttonFiltreParking);
  gtk_widget_set_size_request (buttonFiltreParking, 66, 29);

  image6 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (buttonFiltreParking), image6);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox9, 304, 72);
  gtk_widget_set_size_request (eventbox9, 259, 50);

  label1 = gtk_label_new (_("<big><b><span color='#842431'>G\303\251rer Parking</span></b></big>"));
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (eventbox9), label1);
  gtk_widget_set_size_request (label1, 259, 50);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox10, 32, 32);
  gtk_widget_set_size_request (eventbox10, 66, 29);

  buttonReturnMenuParking = gtk_button_new ();
  gtk_widget_show (buttonReturnMenuParking);
  gtk_container_add (GTK_CONTAINER (eventbox10), buttonReturnMenuParking);
  gtk_widget_set_size_request (buttonReturnMenuParking, 66, 29);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (buttonReturnMenuParking), image8);

  g_signal_connect ((gpointer) treeviewParkingHome, "row_activated",
                    G_CALLBACK (on_treeviewParkingHome_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouterParkingW, "clicked",
                    G_CALLBACK (on_buttonAjouterParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonStatistiqueParkingW, "clicked",
                    G_CALLBACK (on_buttonStatistiqueParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierParkingW, "clicked",
                    G_CALLBACK (on_buttonModifierParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimerParkingW, "clicked",
                    G_CALLBACK (on_buttonSupprimerParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonActualiserParkingW, "clicked",
                    G_CALLBACK (on_buttonActualiserParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercheParking, "clicked",
                    G_CALLBACK (on_buttonRechercheParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonFiltreParking, "clicked",
                    G_CALLBACK (on_buttonFiltreParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonReturnMenuParking, "clicked",
                    G_CALLBACK (on_buttonReturnMenuParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingHome, windowParkingHome, "windowParkingHome");
  GLADE_HOOKUP_OBJECT (windowParkingHome, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, treeviewParkingHome, "treeviewParkingHome");
  GLADE_HOOKUP_OBJECT (windowParkingHome, ParkingSearchTextField, "ParkingSearchTextField");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonAjouterParkingW, "buttonAjouterParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonStatistiqueParkingW, "buttonStatistiqueParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonModifierParkingW, "buttonModifierParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonSupprimerParkingW, "buttonSupprimerParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonActualiserParkingW, "buttonActualiserParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonRechercheParking, "buttonRechercheParking");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (windowParkingHome, ParkingFiltreTextField, "ParkingFiltreTextField");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonFiltreParking, "buttonFiltreParking");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonReturnMenuParking, "buttonReturnMenuParking");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image8, "image8");

  return windowParkingHome;
}

GtkWidget*
create_windowParkingSup (void)
{
  GtkWidget *windowParkingSup;
  GtkWidget *fixed2;
  GtkWidget *textIdSupParking;
  GtkWidget *eventbox11;
  GtkWidget *label7;
  GtkWidget *eventbox12;
  GtkWidget *label8;
  GtkWidget *eventbox13;
  GtkWidget *btnSupParking;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label11;
  GtkWidget *eventbox15;
  GtkWidget *textIdSupParkingControl;
  GtkWidget *eventbox16;
  GtkWidget *btnCancelSupParking;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label10;

  windowParkingSup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowParkingSup, 302, 146);
  gtk_window_set_title (GTK_WINDOW (windowParkingSup), _("Supprimer Parking"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowParkingSup), fixed2);

  textIdSupParking = gtk_entry_new ();
  gtk_widget_show (textIdSupParking);
  gtk_fixed_put (GTK_FIXED (fixed2), textIdSupParking, 184, 72);
  gtk_widget_set_size_request (textIdSupParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textIdSupParking), 8226);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox11, 80, 80);
  gtk_widget_set_size_request (eventbox11, 101, 17);

  label7 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label7);
  gtk_container_add (GTK_CONTAINER (eventbox11), label7);
  gtk_widget_set_size_request (label7, 101, 17);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox12, 120, 32);
  gtk_widget_set_size_request (eventbox12, 240, 24);

  label8 = gtk_label_new (_("<span foreground=\"#842431\" weight=\"bold\">Supprimer Parking </span>\n"));
  gtk_widget_show (label8);
  gtk_container_add (GTK_CONTAINER (eventbox12), label8);
  gtk_widget_set_size_request (label8, 240, 24);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox13, 272, 184);
  gtk_widget_set_size_request (eventbox13, 120, 40);

  btnSupParking = gtk_button_new ();
  gtk_widget_show (btnSupParking);
  gtk_container_add (GTK_CONTAINER (eventbox13), btnSupParking);
  gtk_widget_set_size_request (btnSupParking, 120, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btnSupParking), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox7), label11, FALSE, FALSE, 0);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox15, 96, 144);
  gtk_widget_set_size_request (eventbox15, 332, 17);

  textIdSupParkingControl = gtk_label_new ("");
  gtk_widget_show (textIdSupParkingControl);
  gtk_container_add (GTK_CONTAINER (eventbox15), textIdSupParkingControl);
  gtk_widget_set_size_request (textIdSupParkingControl, 332, 17);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox16, 120, 184);
  gtk_widget_set_size_request (eventbox16, 120, 40);

  btnCancelSupParking = gtk_button_new ();
  gtk_widget_show (btnCancelSupParking);
  gtk_container_add (GTK_CONTAINER (eventbox16), btnCancelSupParking);
  gtk_widget_set_size_request (btnCancelSupParking, 120, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btnCancelSupParking), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox6), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btnSupParking, "clicked",
                    G_CALLBACK (on_btnSupParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnCancelSupParking, "clicked",
                    G_CALLBACK (on_btnCancelSupParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingSup, windowParkingSup, "windowParkingSup");
  GLADE_HOOKUP_OBJECT (windowParkingSup, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowParkingSup, textIdSupParking, "textIdSupParking");
  GLADE_HOOKUP_OBJECT (windowParkingSup, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowParkingSup, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowParkingSup, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (windowParkingSup, btnSupParking, "btnSupParking");
  GLADE_HOOKUP_OBJECT (windowParkingSup, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowParkingSup, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowParkingSup, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowParkingSup, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (windowParkingSup, textIdSupParkingControl, "textIdSupParkingControl");
  GLADE_HOOKUP_OBJECT (windowParkingSup, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (windowParkingSup, btnCancelSupParking, "btnCancelSupParking");
  GLADE_HOOKUP_OBJECT (windowParkingSup, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowParkingSup, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowParkingSup, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label10, "label10");

  return windowParkingSup;
}

GtkWidget*
create_windowParkingAjout (void)
{
  GtkWidget *windowParkingAjout;
  GtkWidget *fixed3;
  GtkWidget *textIdAjoutParking;
  GtkObject *spinCapaciteAjoutParking_adj;
  GtkWidget *spinCapaciteAjoutParking;
  GtkWidget *textNomAjoutParking;
  GtkObject *spinTarifAjoutParking_adj;
  GtkWidget *spinTarifAjoutParking;
  GtkWidget *eventbox17;
  GtkWidget *label17;
  GtkWidget *eventbox18;
  GtkWidget *label12;
  GtkWidget *eventbox19;
  GtkWidget *label18;
  GtkWidget *eventbox20;
  GtkWidget *label19;
  GtkWidget *eventbox21;
  GtkWidget *label21;
  GtkWidget *eventbox22;
  GtkWidget *label29;
  GtkWidget *eventbox23;
  GtkWidget *label23;
  GtkWidget *eventbox24;
  GtkWidget *label24;
  GtkWidget *eventbox25;
  GtkWidget *comboAdresseAjoutParking;
  GtkWidget *eventbox26;
  GtkWidget *radioHoraireAjoutParking;
  GSList *radioHoraireAjoutParking_group = NULL;
  GtkWidget *eventbox27;
  GtkWidget *checkSecOuiAjoutParking;
  GtkWidget *eventbox28;
  GtkWidget *radioJournalierAjoutParking;
  GtkWidget *eventbox29;
  GtkWidget *checkSecNonAjoutParking;
  GtkWidget *eventbox30;
  GtkWidget *windowParkingAjoutControl;
  GtkWidget *eventbox31;
  GtkWidget *btnCancelAjoutParking;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label26;
  GtkWidget *eventbox32;
  GtkWidget *btnAjoutParking;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label25;

  windowParkingAjout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowParkingAjout, 800, 731);
  gtk_window_set_title (GTK_WINDOW (windowParkingAjout), _("Ajouter Parking"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowParkingAjout), fixed3);

  textIdAjoutParking = gtk_entry_new ();
  gtk_widget_show (textIdAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), textIdAjoutParking, 344, 128);
  gtk_widget_set_size_request (textIdAjoutParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textIdAjoutParking), 8226);

  spinCapaciteAjoutParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinCapaciteAjoutParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinCapaciteAjoutParking_adj), 1, 0);
  gtk_widget_show (spinCapaciteAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), spinCapaciteAjoutParking, 400, 312);
  gtk_widget_set_size_request (spinCapaciteAjoutParking, 60, 27);

  textNomAjoutParking = gtk_entry_new ();
  gtk_widget_show (textNomAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), textNomAjoutParking, 344, 184);
  gtk_widget_set_size_request (textNomAjoutParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textNomAjoutParking), 8226);

  spinTarifAjoutParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinTarifAjoutParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinTarifAjoutParking_adj), 1, 0);
  gtk_widget_show (spinTarifAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), spinTarifAjoutParking, 400, 376);
  gtk_widget_set_size_request (spinTarifAjoutParking, 60, 27);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox17, 312, 40);
  gtk_widget_set_size_request (eventbox17, 217, 32);

  label17 = gtk_label_new (_("<span foreground=\"#842431\" weight=\"bold\">Ajouter Parking</span>"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox17), label17);
  gtk_widget_set_size_request (label17, 217, 32);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox18, 216, 136);
  gtk_widget_set_size_request (eventbox18, 103, 17);

  label12 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (eventbox18), label12);
  gtk_widget_set_size_request (label12, 103, 17);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox19, 240, 192);
  gtk_widget_set_size_request (eventbox19, 62, 17);

  label18 = gtk_label_new (_("nom"));
  gtk_widget_show (label18);
  gtk_container_add (GTK_CONTAINER (eventbox19), label18);
  gtk_widget_set_size_request (label18, 62, 17);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox20, 240, 248);
  gtk_widget_set_size_request (eventbox20, 66, 17);

  label19 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label19);
  gtk_container_add (GTK_CONTAINER (eventbox20), label19);
  gtk_widget_set_size_request (label19, 66, 17);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox21, 192, 320);
  gtk_widget_set_size_request (eventbox21, 177, 17);

  label21 = gtk_label_new (_("Capacit\303\251"));
  gtk_widget_show (label21);
  gtk_container_add (GTK_CONTAINER (eventbox21), label21);
  gtk_widget_set_size_request (label21, 177, 17);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox22, 184, 384);
  gtk_widget_set_size_request (eventbox22, 177, 17);

  label29 = gtk_label_new (_("Tarif"));
  gtk_widget_show (label29);
  gtk_container_add (GTK_CONTAINER (eventbox22), label29);
  gtk_widget_set_size_request (label29, 177, 17);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox23, 144, 456);
  gtk_widget_set_size_request (eventbox23, 168, 17);

  label23 = gtk_label_new (_("Type tarifaire"));
  gtk_widget_show (label23);
  gtk_container_add (GTK_CONTAINER (eventbox23), label23);
  gtk_widget_set_size_request (label23, 168, 17);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox24, 152, 504);
  gtk_widget_set_size_request (eventbox24, 168, 17);

  label24 = gtk_label_new (_("Securit\303\251 disponible"));
  gtk_widget_show (label24);
  gtk_container_add (GTK_CONTAINER (eventbox24), label24);
  gtk_widget_set_size_request (label24, 168, 17);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox25, 344, 240);
  gtk_widget_set_size_request (eventbox25, 189, 29);

  comboAdresseAjoutParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboAdresseAjoutParking);
  gtk_container_add (GTK_CONTAINER (eventbox25), comboAdresseAjoutParking);
  gtk_widget_set_size_request (comboAdresseAjoutParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("monastir"));

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox26, 328, 456);
  gtk_widget_set_size_request (eventbox26, 116, 24);

  radioHoraireAjoutParking = gtk_radio_button_new_with_mnemonic (NULL, _("Horaire"));
  gtk_widget_show (radioHoraireAjoutParking);
  gtk_container_add (GTK_CONTAINER (eventbox26), radioHoraireAjoutParking);
  gtk_widget_set_size_request (radioHoraireAjoutParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHoraireAjoutParking), radioHoraireAjoutParking_group);
  radioHoraireAjoutParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHoraireAjoutParking));

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox27, 328, 496);
  gtk_widget_set_size_request (eventbox27, 118, 24);

  checkSecOuiAjoutParking = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkSecOuiAjoutParking);
  gtk_container_add (GTK_CONTAINER (eventbox27), checkSecOuiAjoutParking);
  gtk_widget_set_size_request (checkSecOuiAjoutParking, 118, 24);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox28, 520, 456);
  gtk_widget_set_size_request (eventbox28, 116, 24);

  radioJournalierAjoutParking = gtk_radio_button_new_with_mnemonic (NULL, _("journalier"));
  gtk_widget_show (radioJournalierAjoutParking);
  gtk_container_add (GTK_CONTAINER (eventbox28), radioJournalierAjoutParking);
  gtk_widget_set_size_request (radioJournalierAjoutParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJournalierAjoutParking), radioHoraireAjoutParking_group);
  radioHoraireAjoutParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJournalierAjoutParking));

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox29, 512, 496);
  gtk_widget_set_size_request (eventbox29, 118, 24);

  checkSecNonAjoutParking = gtk_check_button_new_with_mnemonic (_("non"));
  gtk_widget_show (checkSecNonAjoutParking);
  gtk_container_add (GTK_CONTAINER (eventbox29), checkSecNonAjoutParking);
  gtk_widget_set_size_request (checkSecNonAjoutParking, 118, 24);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox30, 216, 600);
  gtk_widget_set_size_request (eventbox30, 473, 17);

  windowParkingAjoutControl = gtk_label_new ("");
  gtk_widget_show (windowParkingAjoutControl);
  gtk_container_add (GTK_CONTAINER (eventbox30), windowParkingAjoutControl);
  gtk_widget_set_size_request (windowParkingAjoutControl, 473, 17);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox31, 224, 664);
  gtk_widget_set_size_request (eventbox31, 168, 40);

  btnCancelAjoutParking = gtk_button_new ();
  gtk_widget_show (btnCancelAjoutParking);
  gtk_container_add (GTK_CONTAINER (eventbox31), btnCancelAjoutParking);
  gtk_widget_set_size_request (btnCancelAjoutParking, 168, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (btnCancelAjoutParking), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox32, 464, 664);
  gtk_widget_set_size_request (eventbox32, 168, 40);

  btnAjoutParking = gtk_button_new ();
  gtk_widget_show (btnAjoutParking);
  gtk_container_add (GTK_CONTAINER (eventbox32), btnAjoutParking);
  gtk_widget_set_size_request (btnAjoutParking, 168, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btnAjoutParking), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox8), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radioHoraireAjoutParking, "toggled",
                    G_CALLBACK (on_radioHoraireAjoutParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkSecOuiAjoutParking, "toggled",
                    G_CALLBACK (on_checkSecOuiAjoutParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJournalierAjoutParking, "toggled",
                    G_CALLBACK (on_radioJournalierAjoutParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkSecNonAjoutParking, "toggled",
                    G_CALLBACK (on_checkSecNonAjoutParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnCancelAjoutParking, "clicked",
                    G_CALLBACK (on_btnCancelAjoutParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAjoutParking, "clicked",
                    G_CALLBACK (on_btnAjoutParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingAjout, windowParkingAjout, "windowParkingAjout");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, textIdAjoutParking, "textIdAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, spinCapaciteAjoutParking, "spinCapaciteAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, textNomAjoutParking, "textNomAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, spinTarifAjoutParking, "spinTarifAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label17, "label17");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label18, "label18");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label19, "label19");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label21, "label21");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label23, "label23");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, comboAdresseAjoutParking, "comboAdresseAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, radioHoraireAjoutParking, "radioHoraireAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, checkSecOuiAjoutParking, "checkSecOuiAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, radioJournalierAjoutParking, "radioJournalierAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, checkSecNonAjoutParking, "checkSecNonAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, windowParkingAjoutControl, "windowParkingAjoutControl");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, btnCancelAjoutParking, "btnCancelAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label26, "label26");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, btnAjoutParking, "btnAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label25, "label25");

  return windowParkingAjout;
}

GtkWidget*
create_windowParkingModif (void)
{
  GtkWidget *windowParkingModif;
  GtkWidget *fixed4;
  GtkWidget *textIdModifParking;
  GtkObject *spinCapaciteModifParking_adj;
  GtkWidget *spinCapaciteModifParking;
  GtkWidget *textNomModifParking;
  GtkObject *spinTarifModifParking_adj;
  GtkWidget *spinTarifModifParking;
  GtkWidget *eventbox33;
  GtkWidget *label30;
  GtkWidget *eventbox34;
  GtkWidget *label37;
  GtkWidget *eventbox35;
  GtkWidget *label35;
  GtkWidget *eventbox36;
  GtkWidget *label36;
  GtkWidget *eventbox37;
  GtkWidget *label34;
  GtkWidget *eventbox38;
  GtkWidget *label32;
  GtkWidget *eventbox39;
  GtkWidget *label33;
  GtkWidget *eventbox40;
  GtkWidget *label31;
  GtkWidget *eventbox41;
  GtkWidget *buttonParkinghercheRecModif;
  GtkWidget *image17;
  GtkWidget *eventbox42;
  GtkWidget *comboAdresseModifParking;
  GtkWidget *eventbox43;
  GtkWidget *radioHoraireModifParking;
  GSList *radioHoraireModifParking_group = NULL;
  GtkWidget *eventbox44;
  GtkWidget *radioJournalierModifParking;
  GtkWidget *eventbox45;
  GtkWidget *checkSecOuiModifParking;
  GtkWidget *eventbox46;
  GtkWidget *checkSecNonModifParking;
  GtkWidget *eventbox47;
  GtkWidget *windowParkingModifControl;
  GtkWidget *eventbox48;
  GtkWidget *btnCancelModifParking;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label39;
  GtkWidget *eventbox49;
  GtkWidget *btnModifParking;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label41;

  windowParkingModif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowParkingModif, 800, 731);
  gtk_window_set_title (GTK_WINDOW (windowParkingModif), _("Modifier Parking"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowParkingModif), fixed4);

  textIdModifParking = gtk_entry_new ();
  gtk_widget_show (textIdModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), textIdModifParking, 344, 128);
  gtk_widget_set_size_request (textIdModifParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textIdModifParking), 8226);

  spinCapaciteModifParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinCapaciteModifParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinCapaciteModifParking_adj), 1, 0);
  gtk_widget_show (spinCapaciteModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), spinCapaciteModifParking, 400, 312);
  gtk_widget_set_size_request (spinCapaciteModifParking, 60, 27);

  textNomModifParking = gtk_entry_new ();
  gtk_widget_show (textNomModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), textNomModifParking, 344, 184);
  gtk_widget_set_size_request (textNomModifParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textNomModifParking), 8226);

  spinTarifModifParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinTarifModifParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinTarifModifParking_adj), 1, 0);
  gtk_widget_show (spinTarifModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), spinTarifModifParking, 400, 376);
  gtk_widget_set_size_request (spinTarifModifParking, 60, 27);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox33, 216, 136);
  gtk_widget_set_size_request (eventbox33, 103, 17);

  label30 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label30);
  gtk_container_add (GTK_CONTAINER (eventbox33), label30);
  gtk_widget_set_size_request (label30, 103, 17);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox34, 240, 192);
  gtk_widget_set_size_request (eventbox34, 62, 17);

  label37 = gtk_label_new (_("nom"));
  gtk_widget_show (label37);
  gtk_container_add (GTK_CONTAINER (eventbox34), label37);
  gtk_widget_set_size_request (label37, 62, 17);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox35, 240, 248);
  gtk_widget_set_size_request (eventbox35, 66, 17);

  label35 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label35);
  gtk_container_add (GTK_CONTAINER (eventbox35), label35);
  gtk_widget_set_size_request (label35, 66, 17);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox36, 192, 320);
  gtk_widget_set_size_request (eventbox36, 177, 17);

  label36 = gtk_label_new (_("Capacit\303\251"));
  gtk_widget_show (label36);
  gtk_container_add (GTK_CONTAINER (eventbox36), label36);
  gtk_widget_set_size_request (label36, 177, 17);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox37, 184, 384);
  gtk_widget_set_size_request (eventbox37, 177, 17);

  label34 = gtk_label_new (_("Tarif"));
  gtk_widget_show (label34);
  gtk_container_add (GTK_CONTAINER (eventbox37), label34);
  gtk_widget_set_size_request (label34, 177, 17);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox38, 144, 456);
  gtk_widget_set_size_request (eventbox38, 168, 17);

  label32 = gtk_label_new (_("Type tarifaire"));
  gtk_widget_show (label32);
  gtk_container_add (GTK_CONTAINER (eventbox38), label32);
  gtk_widget_set_size_request (label32, 168, 17);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox39, 152, 504);
  gtk_widget_set_size_request (eventbox39, 168, 17);

  label33 = gtk_label_new (_("Securit\303\251 disponible"));
  gtk_widget_show (label33);
  gtk_container_add (GTK_CONTAINER (eventbox39), label33);
  gtk_widget_set_size_request (label33, 168, 17);

  eventbox40 = gtk_event_box_new ();
  gtk_widget_show (eventbox40);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox40, 312, 40);
  gtk_widget_set_size_request (eventbox40, 217, 32);

  label31 = gtk_label_new (_("<span foreground=\"#842431\" weight=\"bold\">Modifier Parking</span>"));
  gtk_widget_show (label31);
  gtk_container_add (GTK_CONTAINER (eventbox40), label31);
  gtk_widget_set_size_request (label31, 217, 32);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  eventbox41 = gtk_event_box_new ();
  gtk_widget_show (eventbox41);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox41, 544, 128);
  gtk_widget_set_size_request (eventbox41, 74, 29);

  buttonParkinghercheRecModif = gtk_button_new ();
  gtk_widget_show (buttonParkinghercheRecModif);
  gtk_container_add (GTK_CONTAINER (eventbox41), buttonParkinghercheRecModif);
  gtk_widget_set_size_request (buttonParkinghercheRecModif, 74, 29);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (buttonParkinghercheRecModif), image17);

  eventbox42 = gtk_event_box_new ();
  gtk_widget_show (eventbox42);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox42, 344, 240);
  gtk_widget_set_size_request (eventbox42, 189, 29);

  comboAdresseModifParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboAdresseModifParking);
  gtk_container_add (GTK_CONTAINER (eventbox42), comboAdresseModifParking);
  gtk_widget_set_size_request (comboAdresseModifParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("monastir"));

  eventbox43 = gtk_event_box_new ();
  gtk_widget_show (eventbox43);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox43, 352, 456);
  gtk_widget_set_size_request (eventbox43, 116, 24);

  radioHoraireModifParking = gtk_radio_button_new_with_mnemonic (NULL, _("Horaire"));
  gtk_widget_show (radioHoraireModifParking);
  gtk_container_add (GTK_CONTAINER (eventbox43), radioHoraireModifParking);
  gtk_widget_set_size_request (radioHoraireModifParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHoraireModifParking), radioHoraireModifParking_group);
  radioHoraireModifParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHoraireModifParking));

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox44, 552, 456);
  gtk_widget_set_size_request (eventbox44, 116, 24);

  radioJournalierModifParking = gtk_radio_button_new_with_mnemonic (NULL, _("journalier"));
  gtk_widget_show (radioJournalierModifParking);
  gtk_container_add (GTK_CONTAINER (eventbox44), radioJournalierModifParking);
  gtk_widget_set_size_request (radioJournalierModifParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJournalierModifParking), radioHoraireModifParking_group);
  radioHoraireModifParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJournalierModifParking));

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox45, 352, 496);
  gtk_widget_set_size_request (eventbox45, 118, 24);

  checkSecOuiModifParking = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkSecOuiModifParking);
  gtk_container_add (GTK_CONTAINER (eventbox45), checkSecOuiModifParking);
  gtk_widget_set_size_request (checkSecOuiModifParking, 118, 24);

  eventbox46 = gtk_event_box_new ();
  gtk_widget_show (eventbox46);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox46, 552, 496);
  gtk_widget_set_size_request (eventbox46, 118, 24);

  checkSecNonModifParking = gtk_check_button_new_with_mnemonic (_("non"));
  gtk_widget_show (checkSecNonModifParking);
  gtk_container_add (GTK_CONTAINER (eventbox46), checkSecNonModifParking);
  gtk_widget_set_size_request (checkSecNonModifParking, 118, 24);

  eventbox47 = gtk_event_box_new ();
  gtk_widget_show (eventbox47);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox47, 216, 600);
  gtk_widget_set_size_request (eventbox47, 473, 17);

  windowParkingModifControl = gtk_label_new ("");
  gtk_widget_show (windowParkingModifControl);
  gtk_container_add (GTK_CONTAINER (eventbox47), windowParkingModifControl);
  gtk_widget_set_size_request (windowParkingModifControl, 473, 17);

  eventbox48 = gtk_event_box_new ();
  gtk_widget_show (eventbox48);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox48, 224, 664);
  gtk_widget_set_size_request (eventbox48, 168, 40);

  btnCancelModifParking = gtk_button_new ();
  gtk_widget_show (btnCancelModifParking);
  gtk_container_add (GTK_CONTAINER (eventbox48), btnCancelModifParking);
  gtk_widget_set_size_request (btnCancelModifParking, 168, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (btnCancelModifParking), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox12), label39, FALSE, FALSE, 0);

  eventbox49 = gtk_event_box_new ();
  gtk_widget_show (eventbox49);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox49, 464, 664);
  gtk_widget_set_size_request (eventbox49, 168, 40);

  btnModifParking = gtk_button_new ();
  gtk_widget_show (btnModifParking);
  gtk_container_add (GTK_CONTAINER (eventbox49), btnModifParking);
  gtk_widget_set_size_request (btnModifParking, 168, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (btnModifParking), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonParkinghercheRecModif, "clicked",
                    G_CALLBACK (on_buttonParkinghercheRecModif_clicked),
                    NULL);
  g_signal_connect ((gpointer) radioHoraireModifParking, "toggled",
                    G_CALLBACK (on_radioHoraireModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJournalierModifParking, "toggled",
                    G_CALLBACK (on_radioJournalierModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkSecOuiModifParking, "toggled",
                    G_CALLBACK (on_checkSecOuiModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkSecNonModifParking, "toggled",
                    G_CALLBACK (on_checkSecNonModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnCancelModifParking, "clicked",
                    G_CALLBACK (on_btnCancelModifParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnModifParking, "clicked",
                    G_CALLBACK (on_btnModifParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingModif, windowParkingModif, "windowParkingModif");
  GLADE_HOOKUP_OBJECT (windowParkingModif, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowParkingModif, textIdModifParking, "textIdModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, spinCapaciteModifParking, "spinCapaciteModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, textNomModifParking, "textNomModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, spinTarifModifParking, "spinTarifModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label37, "label37");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label35, "label35");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label32, "label32");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label33, "label33");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox40, "eventbox40");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label31, "label31");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox41, "eventbox41");
  GLADE_HOOKUP_OBJECT (windowParkingModif, buttonParkinghercheRecModif, "buttonParkinghercheRecModif");
  GLADE_HOOKUP_OBJECT (windowParkingModif, image17, "image17");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox42, "eventbox42");
  GLADE_HOOKUP_OBJECT (windowParkingModif, comboAdresseModifParking, "comboAdresseModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox43, "eventbox43");
  GLADE_HOOKUP_OBJECT (windowParkingModif, radioHoraireModifParking, "radioHoraireModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (windowParkingModif, radioJournalierModifParking, "radioJournalierModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (windowParkingModif, checkSecOuiModifParking, "checkSecOuiModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox46, "eventbox46");
  GLADE_HOOKUP_OBJECT (windowParkingModif, checkSecNonModifParking, "checkSecNonModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox47, "eventbox47");
  GLADE_HOOKUP_OBJECT (windowParkingModif, windowParkingModifControl, "windowParkingModifControl");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox48, "eventbox48");
  GLADE_HOOKUP_OBJECT (windowParkingModif, btnCancelModifParking, "btnCancelModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowParkingModif, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowParkingModif, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label39, "label39");
  GLADE_HOOKUP_OBJECT (windowParkingModif, eventbox49, "eventbox49");
  GLADE_HOOKUP_OBJECT (windowParkingModif, btnModifParking, "btnModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowParkingModif, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowParkingModif, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label41, "label41");

  return windowParkingModif;
}

GtkWidget*
create_windowParkingAffectation (void)
{
  GtkWidget *windowParkingAffectation;
  GtkWidget *fixed5;
  GtkWidget *eventbox50;
  GtkWidget *comboIdParkingAffectParking;
  GtkWidget *eventbox51;
  GtkWidget *label42;
  GtkWidget *eventbox52;
  GtkWidget *label43;
  GtkWidget *eventbox53;
  GtkWidget *comboIdAgentAffectParking;
  GtkWidget *eventbox54;
  GtkWidget *label47;
  GtkWidget *eventbox55;
  GtkWidget *btnAffectationParking;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image18;
  GtkWidget *label44;
  GtkWidget *eventbox56;
  GtkWidget *btnCancelAffectationParking;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label45;
  GtkWidget *eventbox57;
  GtkWidget *textIdAffectationParkingControl;

  windowParkingAffectation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowParkingAffectation), _("Affectaion Agent Parking"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowParkingAffectation), fixed5);
  gtk_widget_set_size_request (fixed5, 675, 520);

  eventbox50 = gtk_event_box_new ();
  gtk_widget_show (eventbox50);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox50, 248, 128);
  gtk_widget_set_size_request (eventbox50, 189, 29);

  comboIdParkingAffectParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboIdParkingAffectParking);
  gtk_container_add (GTK_CONTAINER (eventbox50), comboIdParkingAffectParking);
  gtk_widget_set_size_request (comboIdParkingAffectParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("6"));

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox51, 64, 136);
  gtk_widget_set_size_request (eventbox51, 177, 17);

  label42 = gtk_label_new (_("Identifant parking"));
  gtk_widget_show (label42);
  gtk_container_add (GTK_CONTAINER (eventbox51), label42);
  gtk_widget_set_size_request (label42, 177, 17);

  eventbox52 = gtk_event_box_new ();
  gtk_widget_show (eventbox52);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox52, 96, 224);
  gtk_widget_set_size_request (eventbox52, 142, 17);

  label43 = gtk_label_new (_("identifiant Agent"));
  gtk_widget_show (label43);
  gtk_container_add (GTK_CONTAINER (eventbox52), label43);
  gtk_widget_set_size_request (label43, 142, 17);

  eventbox53 = gtk_event_box_new ();
  gtk_widget_show (eventbox53);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox53, 248, 216);
  gtk_widget_set_size_request (eventbox53, 189, 29);

  comboIdAgentAffectParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboIdAgentAffectParking);
  gtk_container_add (GTK_CONTAINER (eventbox53), comboIdAgentAffectParking);
  gtk_widget_set_size_request (comboIdAgentAffectParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN123456"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN789012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN345678"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN901234"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN567890"));

  eventbox54 = gtk_event_box_new ();
  gtk_widget_show (eventbox54);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox54, 224, 24);
  gtk_widget_set_size_request (eventbox54, 243, 67);

  label47 = gtk_label_new (_("<span foreground=\"#842431\" weight=\"bold\">\nAffecter Agent Parking</span>"));
  gtk_widget_show (label47);
  gtk_container_add (GTK_CONTAINER (eventbox54), label47);
  gtk_widget_set_size_request (label47, 243, 67);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  eventbox55 = gtk_event_box_new ();
  gtk_widget_show (eventbox55);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox55, 64, 344);
  gtk_widget_set_size_request (eventbox55, 192, 32);

  btnAffectationParking = gtk_button_new ();
  gtk_widget_show (btnAffectationParking);
  gtk_container_add (GTK_CONTAINER (eventbox55), btnAffectationParking);
  gtk_widget_set_size_request (btnAffectationParking, 192, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btnAffectationParking), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox14), image18, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox56, 64, 400);
  gtk_widget_set_size_request (eventbox56, 192, 32);

  btnCancelAffectationParking = gtk_button_new ();
  gtk_widget_show (btnCancelAffectationParking);
  gtk_container_add (GTK_CONTAINER (eventbox56), btnCancelAffectationParking);
  gtk_widget_set_size_request (btnCancelAffectationParking, 192, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btnCancelAffectationParking), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox15), label45, FALSE, FALSE, 0);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox57, 152, 288);
  gtk_widget_set_size_request (eventbox57, 391, 17);

  textIdAffectationParkingControl = gtk_label_new ("");
  gtk_widget_show (textIdAffectationParkingControl);
  gtk_container_add (GTK_CONTAINER (eventbox57), textIdAffectationParkingControl);
  gtk_widget_set_size_request (textIdAffectationParkingControl, 391, 17);

  g_signal_connect ((gpointer) btnAffectationParking, "clicked",
                    G_CALLBACK (on_btnAffectationParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnCancelAffectationParking, "clicked",
                    G_CALLBACK (on_btnCancelAffectationParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingAffectation, windowParkingAffectation, "windowParkingAffectation");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox50, "eventbox50");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, comboIdParkingAffectParking, "comboIdParkingAffectParking");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label42, "label42");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox52, "eventbox52");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label43, "label43");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox53, "eventbox53");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, comboIdAgentAffectParking, "comboIdAgentAffectParking");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox54, "eventbox54");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label47, "label47");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox55, "eventbox55");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, btnAffectationParking, "btnAffectationParking");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, image18, "image18");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label44, "label44");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, btnCancelAffectationParking, "btnCancelAffectationParking");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, image19, "image19");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label45, "label45");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, textIdAffectationParkingControl, "textIdAffectationParkingControl");

  return windowParkingAffectation;
}

